<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>e603ac88-d59d-4a82-9a26-775c725333ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#two-step-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='two-step-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48c1cbf0-7ce5-4382-91bf-915184a55866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form__submit form__submit--stretch</value>
      <webElementGuid>5ab080f5-0c12-42da-b4ae-5d25d700fda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>two-step-submit-button</value>
      <webElementGuid>692f5346-34c8-4a15-9896-59f538afa6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Submit code</value>
      <webElementGuid>0c5a27d7-2e68-480f-b6e4-93783be5e3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>db084f1e-091b-4a79-a4e4-c49ac269164f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Submit
        </value>
      <webElementGuid>64f3ffc3-47fc-47ac-8b2f-0f7c0947d0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;two-step-challenge&quot;)/div[@class=&quot;form__action&quot;]/button[@id=&quot;two-step-submit-button&quot;]</value>
      <webElementGuid>fa574911-e772-4af9-b447-2fb3ec4742d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='two-step-submit-button']</value>
      <webElementGuid>9cae5551-028c-474a-9d54-0340ed300b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='two-step-challenge']/div[2]/button</value>
      <webElementGuid>7251bd74-4bc9-46bb-9dae-e0108edde1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recognize this device in future'])[1]/following::button[1]</value>
      <webElementGuid>9248cb25-a1a6-4d44-8add-f4b26122f80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the code you see on your authenticator app'])[1]/following::button[1]</value>
      <webElementGuid>49943712-fc9b-43bc-beab-dc68e3d4e707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='verify your identity.'])[1]/preceding::button[1]</value>
      <webElementGuid>47191d51-680c-4699-bc02-c58d616032a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your 8-digit recovery code'])[1]/preceding::button[1]</value>
      <webElementGuid>dbd609e4-d8fe-4d76-8c89-94e51f6871ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>62347925-ffd7-45a4-ae2b-149e69055db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1a2b99a9-b496-417f-9aeb-1fcb9cc9febd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'two-step-submit-button' and @type = 'submit' and (text() = '
          Submit
        ' or . = '
          Submit
        ')]</value>
      <webElementGuid>5b368252-2c6f-4646-bf1c-b0fb4b11f3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
